# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc8a80d88ee6573553f811df5fa875741b8fcefecdcd0a0ee8fdda816bccb51ebd4f7dee6b383b0aff520d55b7a3b78d809812350699ec5148421bb4436abecb

test:
  secret_key_base: 542a900d9d2e03cfd5f57f858a2ac0cbb3bb27a4dca2e506138d9dff4acef53cb5f81ad51e34d9cd9f3e45418e4a5530e5e661660f8cd5e80339799c264424e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
